table Dim_Calendario
	lineageTag: 1bafc9b1-5d2d-4ef6-b622-6b13f570c995

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 96ea47d9-4834-4241-aac4-67b738e07277
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 2cf22996-3411-43b7-901e-d750330f2d88
			defaultHierarchy: LocalDateTable_d25e2c8f-c0d9-49b4-819e-302705f50615.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 0e6e18bf-7f38-45da-abaf-eae7aa04eee8
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: e26abb69-adb7-41fc-a427-19bd4d9366a8
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 4e864b12-49e4-47b5-9afc-960a3306055f
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 2d872400-6b55-4248-96c7-329d4f459a50
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: c89d92bd-b0d9-4879-8e41-1a42e0056065
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Fabio\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

