table dim_canal
	lineageTag: 4c8f771c-fc87-45f8-a13d-d7a535768cc5

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: fdaa3c4b-6250-4b41-8f5d-7f0280ba8ca5
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: 3c67e188-1c87-4c57-b215-dadad8829aba
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: d99aaf90-7788-48f3-aecd-6da70dbfe0a8
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	partition dim_canal = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Fabio\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_canal_Table = Origen{[Item="dim_canal",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_canal_Table,{{"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

