table dim_vehiculo
	lineageTag: 8936e4a0-9100-4287-b655-f36471cd287a

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 6d02af25-b80f-402d-bcee-75957690fb92
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: a24d094e-d6f1-47a5-9180-abf4699d9ef9
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 3d1ef746-b3ab-417d-bde1-7910a5a46002
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: df301bdf-b526-4e1f-aa75-b24b40994ea0
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column a침o_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: b8d2e22b-a48f-4725-bdb5-73a1da73af32
		summarizeBy: sum
		sourceColumn: a침o_vehiculo

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Fabio\Downloads\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Origen{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"a침o_vehiculo", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegaci칩n

	annotation PBI_ResultType = Table

