table Hoja1
	lineageTag: dba5274d-b634-4172-b0bb-7890427d690a

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: f3b02a8a-3b47-4229-a9fb-efe1e65ab876
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 6e8b0756-30b0-46ea-b2ec-4b03b4e21a2c
			defaultHierarchy: LocalDateTable_936eac0d-8217-4fb8-923b-e6794d6397f8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 557d7e90-cfd5-4269-8428-93994c586488
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: eb71bfa9-db92-49a8-b421-d6e8d8100b65
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 33c0563c-dea6-40ba-8534-20d800b7fbec
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: 531e4cd8-d42d-4938-bc75-1d95392aba1d
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: accef2d9-994f-44ea-8580-fb16ae25b62e
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	column Column7
		dataType: string
		lineageTag: a5eb5542-5222-45d4-a8b0-dc0c48d5bd6f
		summarizeBy: none
		sourceColumn: Column7

		annotation SummarizationSetBy = Automatic

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: fa491202-0a48-40f1-ba72-0754f2829128
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: ba7d872b-03a7-439b-85f9-8e1a46a725c3
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: c24895ba-7d04-42aa-a528-def7710f5a07
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	column Column11
		dataType: string
		lineageTag: 3c8ae311-7b0f-46cf-80ba-dc805678fbbc
		summarizeBy: none
		sourceColumn: Column11

		annotation SummarizationSetBy = Automatic

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 75b5cc84-f387-445c-b593-e68efdb49c79
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: e196e9b4-a1b9-499e-85e4-47a375866275
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 8adac1a9-78e3-4add-b374-356a7c7b021d
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	column Column15
		dataType: string
		lineageTag: d4767aa3-91d5-4edc-9469-c53e67638ff8
		summarizeBy: none
		sourceColumn: Column15

		annotation SummarizationSetBy = Automatic

	column id_Cliente
		dataType: int64
		formatString: 0
		lineageTag: 9fe35994-b58e-4dd7-8a8f-7df582867790
		summarizeBy: none
		sourceColumn: id_Cliente

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: a219546e-d3fd-4023-849a-70651354b1da
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Column18
		dataType: string
		lineageTag: 810550c4-0291-40c2-b4ef-0b456cf68de9
		summarizeBy: none
		sourceColumn: Column18

		annotation SummarizationSetBy = Automatic

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 98c3f875-2bda-43de-af71-439761da4f86
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: ee27e923-e84a-4fac-b66f-ed6a5b01e079
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 03133db3-ecd9-4c4d-b769-f898f031452c
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: 23b16b65-c8d8-4593-987d-27571634004d
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 1feb5869-0ef1-40f4-a8fb-d9c8467181b0
		summarizeBy: sum
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	column Column24
		dataType: string
		lineageTag: 3fa67966-8061-490b-8e65-32eea1ab9e9b
		summarizeBy: none
		sourceColumn: Column24

		annotation SummarizationSetBy = Automatic

	column periodo
		dataType: int64
		formatString: 0
		lineageTag: 2042c404-f273-4bde-addc-0d7f485f4445
		summarizeBy: sum
		sourceColumn: periodo

		annotation SummarizationSetBy = Automatic

	column 'mes.1'
		dataType: string
		lineageTag: 3a3e534d-532a-49cb-9f9e-8b916cc465db
		summarizeBy: none
		sourceColumn: mes.1

		annotation SummarizationSetBy = Automatic

	column id_sede_1
		dataType: int64
		formatString: 0
		lineageTag: d5694ca3-9f88-4df3-9a32-708ec4b3d715
		summarizeBy: sum
		sourceColumn: id_sede_1

		annotation SummarizationSetBy = Automatic

	column ppto
		dataType: int64
		formatString: 0
		lineageTag: 31673594-c7c6-41a6-b16c-575170601a47
		summarizeBy: sum
		sourceColumn: ppto

		annotation SummarizationSetBy = Automatic

	column Column29
		dataType: string
		lineageTag: 5f422182-668b-45b7-a826-3afa2aeae301
		summarizeBy: none
		sourceColumn: Column29

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: bfdb8f32-8b10-444f-99b9-7af6c47a7f5e
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column datekey_2
		dataType: int64
		formatString: 0
		lineageTag: 2b22060a-543c-4150-8f64-8c470f55a105
		summarizeBy: sum
		sourceColumn: datekey_2

		annotation SummarizationSetBy = Automatic

	column 'Canal.1'
		dataType: int64
		formatString: 0
		lineageTag: 6c3fdf12-add2-4661-80a6-64f390bfaa61
		summarizeBy: sum
		sourceColumn: Canal.1

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: int64
		formatString: 0
		lineageTag: e55fddfa-b5c1-4662-b265-07983868f83d
		summarizeBy: sum
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: a3524b9b-7242-40a6-9267-1b3ccaad29e5
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 9015a28d-8316-40f5-96d2-5b2b0aa80945
		summarizeBy: sum
		sourceColumn: Vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo Vehículo'
		dataType: double
		lineageTag: 548c8dc3-c903-4195-9e74-27bf33613be2
		summarizeBy: sum
		sourceColumn: Costo Vehículo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Precio Venta sin IGV'
		dataType: double
		lineageTag: e2f99e28-6c3a-4afc-8ecb-80afc9fb73f3
		summarizeBy: sum
		sourceColumn: Precio Venta sin IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IGV
		dataType: double
		lineageTag: c34f15a9-aee3-4d42-83a2-d423f6e2d7b4
		summarizeBy: sum
		sourceColumn: IGV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sede
		dataType: int64
		formatString: 0
		lineageTag: c467e4b9-ba77-4c59-9046-e30b8495f663
		summarizeBy: sum
		sourceColumn: Sede

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: int64
		formatString: 0
		lineageTag: e4e60b1a-e20e-4141-870d-737b48c57e16
		summarizeBy: sum
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Column41
		dataType: string
		lineageTag: c461e6af-63ce-42d1-a069-95a19d350f4a
		summarizeBy: none
		sourceColumn: Column41

		annotation SummarizationSetBy = Automatic

	column 'Id.1'
		dataType: int64
		formatString: 0
		lineageTag: d08f2da2-d9cd-4623-be49-b58204bd387a
		summarizeBy: sum
		sourceColumn: Id.1

		annotation SummarizationSetBy = Automatic

	column Modelo
		dataType: string
		lineageTag: 38b297d1-0a98-4999-961a-c682a6ff750d
		summarizeBy: none
		sourceColumn: Modelo

		annotation SummarizationSetBy = Automatic

	column Version
		dataType: string
		lineageTag: 6a5bf55b-8d33-48cf-adfd-2186787cf981
		summarizeBy: none
		sourceColumn: Version

		annotation SummarizationSetBy = Automatic

	column Precio
		dataType: int64
		formatString: 0
		lineageTag: 4078c7f1-53a0-4753-bbb5-cfa220ad43ef
		summarizeBy: sum
		sourceColumn: Precio

		annotation SummarizationSetBy = Automatic

	column Imagen
		dataType: string
		lineageTag: 4629ad7a-32d6-4c83-aff0-d006930dc691
		summarizeBy: none
		sourceColumn: Imagen

		annotation SummarizationSetBy = Automatic

	column Column47
		dataType: string
		lineageTag: 6946b2d7-6083-441b-b4a3-5ec211e4e2fb
		summarizeBy: none
		sourceColumn: Column47

		annotation SummarizationSetBy = Automatic

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 739b65ff-a8f3-48ae-a2e7-a21f7f25036c
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor_3
		dataType: string
		lineageTag: 06f509ef-92de-4e8f-a317-9802db05f31d
		summarizeBy: none
		sourceColumn: Vendedor_3

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 42a4fb9e-6e42-4c3b-8c33-e2bdc2b7191d
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variación
			isDefault
			relationship: 375f3597-a132-446b-b7b6-73b530aaa7ee
			defaultHierarchy: LocalDateTable_b2531939-4a8a-4346-94d4-aea098192af9.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: c0324758-8ea0-46da-882e-4a8c86418217
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Hoja1 = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\Fabio\Downloads\VentasVehiculos.xlsx"), null, true),
				    Hoja1_Sheet = Origen{[Item="Hoja1",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Hoja1_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}, {"Column7", type any}, {"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}, {"Column11", type any}, {"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}, {"Column15", type any}, {"id_Cliente", Int64.Type}, {"Nombre", type text}, {"Column18", type any}, {"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}, {"Column24", type any}, {"periodo", Int64.Type}, {"mes", type text}, {"id_sede_1", Int64.Type}, {"ppto", Int64.Type}, {"Column29", type any}, {"ID", Int64.Type}, {"datekey_2", Int64.Type}, {"Canal", Int64.Type}, {"Cliente", Int64.Type}, {"Segmento", type text}, {"Vehiculo", Int64.Type}, {"Costo Vehículo", type number}, {"Precio Venta sin IGV", type number}, {"IGV", type number}, {"Sede", Int64.Type}, {"Vendedor", Int64.Type}, {"Column41", type any}, {"Id", Int64.Type}, {"Modelo", type text}, {"Version", type text}, {"Precio", Int64.Type}, {"Imagen", type text}, {"Column47", type any}, {"ID_Vendedor", Int64.Type}, {"Vendedor_3", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"mes", "mes.1"}, {"Canal", "Canal.1"}, {"Id", "Id.1"}})
				in
				    #"Columnas con nombre cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

